### ISSUE TITLE
Source network gets reset on starting new transfer

### ISSUE THREAD

**Issue by mpetrunic** [sygmaprotocol/sygma-widget#133]
## Expected Behavior
If wallet is still connected we shouldn't reset selected source network.

## Current Behavior
We reset selected source network which ends us in unsupported state where wallet is connected before source network is selected

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Version

Sygma commit (or docker tag):
sygma-solidity version:
sygma-substrate version:
Go version:

**Comment by LyonSsS** [comment]
From my point of view, since the specifications and also Figma design flow, do not specify this behavior, I do consider that a "starting a new transfer" = "initial transfer". Because of this, I do consider the behavior as normal. 
I would be glad with booth ways - restart OR keep the user historical data as it was before ( Source + Dest and TOKEN type selected, but nothing more).
I think this can be of course answered by product.  CC: @itsbobbyzzz168

**Comment by mpetrunic** [comment]
I think question is do we disconnect wallet as well or do we leave source network selected and remove everything else. As those are only two valid states for widget

**Comment by LyonSsS** [comment]
Teste on PR  link
![Restart_Transatcion](https://github.com/sygmaprotocol/sygma-widget/assets/30255634/1cba026b-f450-4b27-a73c-b7fd8117a122)
