### ISSUE TITLE
Wrong Evm amount calculation 

### ISSUE THREAD

**Issue by mpetrunic** [sygmaprotocol/sygma-widget#139]
## Expected Behavior

To match substrate behavior as well as behavior of other token bridges. Bridge fee should be subtracted from user submitted amount to transfer.

## Current Behavior

Bridge fee is added on top of user input amount. And validation doesn't take that into account

## Possible Solution

- fetch fee
- on percentage fee handler
   - calculate percentage fee/input
   - calculate amount: amount=input/(1+feePercentage)
- on fixed fee handler (don't think it's ever in token)
   - amount=input-fee

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Version

Sygma commit (or docker tag):
sygma-solidity version:
sygma-substrate version:
Go version:

**Comment by LyonSsS** [comment]
Percentage fee handler behavior applies % behavior for values that are limited to the minimum and maximum bounds. 
This is the definition of the Percentage Fee Handler for sygUSDC  on spolia 
![image](https://github.com/sygmaprotocol/sygma-widget/assets/30255634/94d6c711-5466-46a1-aebc-41edb432652f)
PerceFeeHandler: https://sepolia.etherscan.io/address/0x2e77dEa116117eCF44a427064260D16D488ccff2#readContract 
For EX - inputting amount 8 to transfer of sygUSDC will span the correct allow spending value ( 1 sygUSDC ) 
![image](https://github.com/sygmaprotocol/sygma-widget/assets/30255634/28cbf935-951b-42e4-9c48-667d4dedc745)
But incorrect for the actual transfer amount ( 7.111 instead of 7)
![image](https://github.com/sygmaprotocol/sygma-widget/assets/30255634/4909e5d9-67c8-4476-987c-ca6baa476b62)

**Comment by mpetrunic** [comment]
I wasn't even aware that percentage handler had min/max bounds 🤦🏻‍♂️

**Comment by mpetrunic** [comment]
Oh noes, I need to modify sdk for that...

**Comment by LyonSsS** [comment]
Also @mpetrunic , please integrate this fix https://github.com/sygmaprotocol/sygma-widget/issues/124 to test this behavior. As MAX value might behave strange. I want to cover it here for booth actual allowance behavior + transfer amount.

**Comment by mpetrunic** [comment]
> Also @mpetrunic , please integrate this fix #124 to test this behavior. As MAX value might behave strange. I want to cover it here for booth actual allowance behavior + transfer amount.

done

**Comment by LyonSsS** [comment]
If I use a token that has a percentage fee approach, if I use the in between value (  min threshold < value < max threshold ), the transfer amount is not correct calculated. This is going to have issues when using the max value. 
Step 1 - use a middle value of which ( in this example it takes 0.1% fee) is calculated via percentage
![image](https://github.com/sygmaprotocol/sygma-widget/assets/30255634/a100f48d-6ae1-4669-a7d0-52e5df81b3a9)
Step 2 - allow spending for the transfer amount ( EXPECTED to work on this logic "calculate amount: amount=input/(1+feePercentage) )  ACTUAL - it calculates the entire value.
![image](https://github.com/sygmaprotocol/sygma-widget/assets/30255634/0706e328-0a74-41ac-ae77-6157064fcd6e)
Step 2 applies to the transfer amount also.

**Comment by LyonSsS** [comment]
Tested on latest Release version - it works fine 
![image](https://github.com/sygmaprotocol/sygma-widget/assets/30255634/30cb9956-0d65-45e4-96c8-d34becc650ca)

**Comment by LyonSsS** [comment]
Retested on core PR main branch - everything works as expected
![image](https://github.com/sygmaprotocol/sygma-widget/assets/30255634/56d12839-6ca4-44f2-a560-8c54fea48822)
